export const COUNTRIES = [
  { code: "DE", name: "Deutschland" },
  { code: "AT", name: "Österreich" },
  { code: "CH", name: "Schweiz" },
  { code: "US", name: "USA" },
  { code: "GB", name: "Vereinigtes Königreich" },
  { code: "FR", name: "Frankreich" },
  { code: "IT", name: "Italien" },
  { code: "ES", name: "Spanien" },
  { code: "NL", name: "Niederlande" },
  { code: "BE", name: "Belgien" },
  { code: "PL", name: "Polen" },
  { code: "PT", name: "Portugal" },
  { code: "SE", name: "Schweden" },
  { code: "NO", name: "Norwegen" },
  { code: "DK", name: "Dänemark" },
  { code: "FI", name: "Finnland" },
  { code: "CZ", name: "Tschechien" },
  { code: "GR", name: "Griechenland" },
  { code: "IE", name: "Irland" },
  { code: "LU", name: "Luxemburg" },
  { code: "CA", name: "Kanada" },
  { code: "AU", name: "Australien" },
  { code: "AE", name: "Vereinigte Arabische Emirate" },
  { code: "SG", name: "Singapur" },
  { code: "JP", name: "Japan" },
  { code: "OTHER", name: "Anderes Land" },
] as const;
